# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: pg-go-hexagonal-example
    container_name: pg-go-hexagonal-example
    restart: always
    build:
      context: ./postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432